//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMSAppDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPMSDevEntities : DbContext
    {
        public EPMSDevEntities()
            : base("name=EPMSDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Performance> Performances { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Record> Records { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Work> Works { get; set; }
    }
}
