//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMSAppDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int Id { get; set; }
        public string Justification { get; set; }
        public string Aims { get; set; }
        public int Grading { get; set; }
        public string Status { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> RecordId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Record Record { get; set; }
    }
}
