//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMSAppDemo.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Works = new HashSet<Work>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] RowVersion { get; set; }
        public bool IsActive { get; set; }
        public bool DevTeam { get; set; }
        public bool ServiceDesk { get; set; }
        public bool Operations { get; set; }
        public bool Communications { get; set; }
        public bool LocalSupportWest { get; set; }
        public bool LocalSupportEast { get; set; }
        public bool LocalSupportNorth { get; set; }
        public bool Admin { get; set; }
        public bool Trainers { get; set; }
        public bool BusinessServicesDelivery { get; set; }
        public bool BusinessServicesAnalysis { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work> Works { get; set; }
    }
}
