//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMSAppDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public string WorkItem { get; set; }
        public string Description { get; set; }
        public decimal HoursWorked { get; set; }
        public Nullable<decimal> HoursRemaining { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public byte[] RowVersion { get; set; }
        public int Work_Record { get; set; }
        public int Work_Project { get; set; }
        public int Work_Category { get; set; }
        public Nullable<int> Late { get; set; }
        public Nullable<System.DateTime> tempTimeBegin { get; set; }
        public Nullable<System.DateTime> tempTimeEnd { get; set; }


        public virtual Category Category { get; set; }
        public virtual Project Project { get; set; }
        public virtual Record Record { get; set; }
    }
}
